// <auto-generated />
namespace eShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddeBasket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddeBasket));
        
        string IMigrationMetadata.Id
        {
            get { return "201808141829102_AddeBasket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
